[package]
name = "server"
version.workspace = true
edition.workspace = true
license = "AGPL-3.0-only"

[dependencies]
bevy = { version = "0.18.0", default-features = false }
ekza-bevy-sdk = { git = "https://github.com/ekza-space/ekza-bevy-sdk", rev = "8254ed5e94d4709c11c83bef604ebe4481467847", default-features = false }
serde.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
omoba-passport = { path = "../passport" }

[lints]
workspace = true
